### ISSUE TITLE
Wrong copyright notice

### ISSUE THREAD

**Issue by Moini** [ThoreMehr/inkscape-OpenTabbedBoxMaker#1]
Hi Thore,

it seems you accidentally removed the original copyright notice by Elliot White, who originally wrote this extension in 2011 (http://www.inkscapeforum.com/viewtopic.php?p=38785). 
Could you please add it back in to comply to the licence, which is GPLv3, so requires anyone who redistributes the code to name all copyright holders?

**Comment by ThoreMehr** [comment]
done
